# Generated by Django 4.0.5 on 2022-07-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='customergoal',
            name='promo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.promotion'),
        ),
    ]
