# Generated by Django 4.0.5 on 2022-07-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_remove_promotion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promo_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
