# Generated by Django 4.0.5 on 2022-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_promotion_promo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergoal',
            name='total_benefit',
            field=models.IntegerField(default=0),
        ),
    ]
