# Generated by Django 4.0.5 on 2022-07-05 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_customergoal_total_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergoal',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 7, 6)),
            preserve_default=False,
        ),
    ]
